Module11 task1
htmlacademy-javascript/2519719-kekstagram-1 pull request #10
Opened 2024-07-17 18:43 UTC by YarinaBarabash

2024-07-23 11:18 UTC, wonderjs requested changes

2024-07-23 11:18 UTC, wonderjs commented on index.html
> +  <template id="global-error">
Ошибка загрузки фотографии по тз не должно блокировать пользователю возможностью загрузить свою фотографию, так что просто возьми функцию showAlert из демки 
![Снимок экрана 2024-07-23 в 13 00 27](https://github.com/user-attachments/assets/dc64ce76-861e-4a51-b99c-080340af0a6c)

2024-07-23 11:18 UTC, wonderjs commented on js/elements.js
> +const body = document.querySelector('body');
излишне выносить в переменную, просто используй `document.body `

2024-07-23 11:18 UTC, wonderjs commented on js/form.js
> +form.addEventListener('submit', async (evt) => {
Лучше сделать функцию установки слушателя на форму, экспортировать и вызвать ее в main.js
```
const setFormSubmit = () => {
  form.addEventListener('submit', async (evt) => {
    evt.preventDefault();
    const isValid = pristine.validate();
    if (isValid) {
      const formData = new FormData(evt.target);
      sendData(formData)
        .then(() => {
          closeForm();
          showModal('success');
        })
        .catch(() => {
          showModal('error');
        });
    }
  });
};
```
также нужно добавить сюда:
![Снимок экрана 2024-07-23 в 13 04 25](https://github.com/user-attachments/assets/a212a094-b72d-4a41-a551-96b0028cc27d)

2024-07-23 11:18 UTC, wonderjs commented on js/util.js
> +const isEscapeKey = (key) => key === 'Escape';
В классическом виде передается evt
```
const isEscapeKey = (evt) => evt.key === 'Escape';
```

2024-07-23 11:18 UTC, wonderjs commented on js/util.js
> +export { createRandomIdFromRangeGenerator, getRandomArrayElement, getRandomInteger, isEscapeKey };
Удалить более не используемые модули (mocks, data) и функции

2024-07-23 11:18 UTC, wonderjs commented on js/messages.js
> +import { body } from './elements.js';
Тк внутри ты оперируешь словом modal, то логично модуль назвать modal.js

2024-07-23 11:18 UTC, wonderjs commented on js/messages.js
> +let onKeydownListener;
Усложнила

1) В index.html добавляем для section с классом error и success ещэ один класс modal, чтобы было легче в доме найти открытую модалку
```
<section class="error modal">
...

<section class="success modal">
...
```

2) Находим шаблоны сообщений об успехе и ошибке
```
const successTemplate = document.querySelector('#success').content.querySelector('.success');
const errorTemplate = document.querySelector('#error').content.querySelector('.error');
```

3) Связываем тип сообщения с шаблоном
```
const modalTypeToTemplate = {
  success: successTemplate,
  error: errorTemplate,
};
```
Это позволит легко выбирать нужный шаблон в зависимости от типа сообщения.

4) Определяем функцию закрытия модального окна
```
const closeModal = () => {
  const modal = document.querySelector('.modal');
  if (modal) {
    modal.remove();
    document.removeEventListener('keydown', onDocumentKeydown);
  }
};
```
Функция closeModal находит модальное окно на странице и удаляет его, если оно существует. Также удаляется обработчик события keydown.

5) Определяем функция показа модального окна
```
const showModal = (type) => {
  const modal = modalTypeToTemplate[type].cloneNode(true);
  const button = modal.querySelector(`.${type}__button`);

  button.addEventListener('click', () => {
    closeModal();
  });

  modal.addEventListener('click', (evt) => {
    if (evt.target === modal) {
      closeModal();
    }
  });

  document.addEventListener('keydown', onDocumentKeydown);
  document.body.appendChild(modal);
};
```
Функция showModal создает и показывает модальное окно. Она принимает параметр type, который может быть success или error. Внутри функции:
- Шаблон клонируется и сохраняется в переменую modal.
- Кнопка внутри модального окна получает обработчик события click, который закрывает модальное окно при нажатии.
- Модальное окно получает обработчик события click, который закрывает окно, если клик был сделан вне области содержимого.
- Добавляется обработчик события keydown для закрытия окна при нажатии клавиши Escape.
- Модальное окно добавляется в тело документа.

6) Определяем обработчик нажатие на клавишу
```
function onDocumentKeydown (evt) {
  if (isEscapeKey(evt)) {
    closeModal();
  }
}
```
Функция onDocumentKeydown проверяет, была ли нажата клавиша Escape с помощью функции isEscapeKey. Если это так, вызывается функция closeModal.

7) Экспортируем функцию showModal
```
export { showModal };
```

2024-07-23 11:18 UTC, wonderjs commented on js/main.js
> +const photos = await getPhotos(() => showModal('#global-error', '.error__button'));
Рендер вызывается только если данные успешно загрузились
```
getPhotos()
  .then((photos) => {
    renderMiniature(photos);
    addPicturesEventListener(photos);
  })
  .catch(
    (err) => {
      showAlert(err.message);
    }
  );
```

2024-07-24 18:41 UTC, YarinaBarabash commented on js/elements.js
> +const body = document.querySelector('body');
хорошо, а почему

2024-07-24 18:53 UTC, YarinaBarabash commented on js/util.js
> +const isEscapeKey = (key) => key === 'Escape';
исправлю, а зачем передается то, что не используется?

2024-07-24 19:01 UTC, wonderjs commented on js/util.js
> +const isEscapeKey = (key) => key === 'Escape';
ИСправлять не обязательно, просто написала какой вариант ты можешь встретить чаще

2024-07-24 19:10 UTC, wonderjs commented on js/elements.js
> +const body = document.querySelector('body');
Это не ошибка, просто кажется, что проще обратиться к body через document, чем таскать переменную из модуля в модуль. 

При обращении к document.body не происходит повторный поиск элемента в DOM. document.body — это свойство объекта document, которое напрямую ссылается на элемент <body> в документе. Оно всегда доступно и возвращает тот же элемент без дополнительных вычислений или поиска в DOM-дереве.

Таким образом, частое использование document.body не создает дополнительных накладных расходов на производительность.

2024-07-25 13:42 UTC, merged