fix + module
htmlacademy-javascript/2519719-kekstagram-1 pull request #4
Opened 2024-05-04 20:40 UTC by YarinaBarabash

2024-05-05 16:09 UTC, wonderjs requested changes

2024-05-05 16:09 UTC, wonderjs commented on js/data.js
> +const MAXAVATARINT = 6;
[Б7.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b7) Названия констант (постоянных значений) написаны прописными (заглавными) буквами. 
Слова разделяются подчёркиваниями (UPPER_SNAKE_CASE)
Либо `MIN_AVATAR` / `MAX_AVATAR`, либо заведи перечисление:
```
const Avatar = {
  MIN: 1,
  MAX: 6
};
```
Аналогично исправить переменные ниже с id и количество комментариев

2024-05-05 16:09 UTC, wonderjs commented on js/photo.js
> +import {MESSAGES, NAMES, DESCRIPTIONS, PHOTO_COUNT, Like, MINAVATARINT, MAXAVATARINT, MINID,
Можно этот модуль объединить с модулем data.js. Можно оставить так, но тогда переименовать в mocks.js, тк далее мы будет создавать модули для создания элементов фото, чтобы добавлять их в DOM и название photo.js для текущего модуля будет вводить в заблуждение.

2024-05-05 16:09 UTC, wonderjs commented on package.json
> +  "type": "module"
А это зачем добавила? Где такое нашла?

2024-05-05 16:09 UTC, wonderjs commented on js/photo.js
> +const generatePhotos = () => Array.from({length: PHOTO_COUNT}, createPhoto);
Экспортируй эту функцию из модуля и перенеси туда вызов generatePhotos

2024-05-14 15:13 UTC, YarinaBarabash commented on package.json
> +  "type": "module"
это чтобы работало в среде разработки)
без этого ошибка была

2024-05-15 15:46 UTC, merged