Открывается и закрывается
htmlacademy-javascript/2519719-kekstagram-1 pull request #6
Opened 2024-06-06 15:55 UTC by YarinaBarabash

---
:mortar_board: [Открывается и закрывается](https://up.htmlacademy.ru/javascript-individual/1/user/2519719/tasks/12)

:boom: https://htmlacademy-javascript.github.io/2519719-kekstagram-1/6/

2024-06-13 10:07 UTC, wonderjs requested changes

2024-06-13 10:07 UTC, wonderjs commented on index.html
> +  <!-- <script src="js/functions.js" type="module"></script> -->
просто удали этот модуль

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +const bigPucrure = document.querySelector('.big-picture');
Опечатка в Picture

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +const buttoncancel = document.querySelector('.big-picture__cancel');
[Б3.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b3) Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  const socialcomment = document.querySelector('.social__text');
[Б3.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b3) Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.
Переменная не используется

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  const listcomments = document.querySelector('.social__comments');
[Б3.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b3) Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  const commentone = document.querySelector('.social__comment');
[Б3.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b3) Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  listcomments.innerHTML='';
Не хватает пробелов между, смотри ошибки линтера перед отправкой на проверку

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  photo.comments.forEach((comment) => {
Лучше рендер комментариев сразу вынести в отдельную функцию

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +    const copycomment = commentone.cloneNode(true);
Лучше в index.html создать темплейт для одного комментария (по аналогии с миниатюрами фото) и клонировать его

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +    listcomments.appendChild(copycomment);
[Б25.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b25) Множественные DOM-операции производятся на элементах, которые не добавлены в DOM.

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  pictureImgs.forEach((pictureEl, index) => {
Лучше добавить один обработчик на контейнер с фото, чем вешать на каждое фото. Здесь у нас всего 25 фотографий, а что если их будет 100000?

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  document.addEventListener('keydown', keydownListener);
[Д4.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d4) Именованные функции-обработчики событий названы в соответствии с правилами именования обработчиков.
Функция-обработчик должна быть объявлена до использования

2024-06-13 10:07 UTC, wonderjs commented on js/fullsize.js
> +  buttoncancel.addEventListener('click', closeModal);
[Д4.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d4) Именованные функции-обработчики событий названы в соответствии с правилами именования обработчиков.

2024-06-13 10:07 UTC, wonderjs commented on js/main.js
> +renderMiniature(photos)
Потеряла точку с запятой

2024-06-13 10:07 UTC, wonderjs commented on js/main.js
> +import { addEventListeners } from './fullsize.js';
Удалить все ненужные испорть

2024-06-13 10:07 UTC, wonderjs commented on js/mocks.js
> +export {generatePhotos, createPhoto};
Зачем экпортируешь createPhoto?

2024-06-22 16:01 UTC, YarinaBarabash commented on js/fullsize.js
> +  buttoncancel.addEventListener('click', closeModal);
тут я не поняла, у меня тут 2 действия, мне их через OR в названии назвать?

2024-06-23 12:50 UTC, wonderjs requested changes

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +function openFullsize (photo) {
[Д5.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d5) Все функции объявлены единообразно.
используем стрелочную нотацию 
лучше и модуль и функцию назвать более понятно - openFullsizePhoto и fullsize-photo.js

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +  const commentOne = document.querySelector('.social__comment');
Все элементы ищем и записываем в переменные вне функции, в начале модуля, чтобы не искать их заново при каждой ее вызове + ищем не по document, а внутри уже найденного элемента `bigPicture`
commentOne -> comment

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +const bigPucture = document.querySelector('.big-picture');
опечатка `bigPicture`

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +  srcBigPicture.src = photo.url;
картинке сразу alt добавляем

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +  listComments.innerHTML='';
Не забывай про линтер, потеряла пробелы вокруг знака `=`

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +  function addListenersOnPhoto() {
Зачем функция? можно убрать и просто повесить обработчики

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +    document.addEventListener('keydown', onDocumentKeydown);
функцию onDocumentKeydown определить через function, чтобы эта функци всплыла

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +    const copycomment = commentOne.cloneNode(true);
[Б3.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b3) Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.
copycomment -> newComment

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +    copycomment.querySelector('.social__text').textContent = '';
зачем сначала задавать пустую строку, а потом уже значение? 
Эта строчка лишняя

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +    listComments.appendChild(copycomment);
[Б25.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b25) Множественные DOM-операции производятся на элементах, которые не добавлены в DOM.
Сначала собери все комментарии в fragment

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +function addEventListeners(photos) {
Используй делегирование, повесь один обработчик на весь контейнер с фото, а не 25 обработчиков на каждую

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +  removeEventListeners();
Сделай функцию closeFullsizePhoto, вынеси туда удалание/добавление классов и удаление обработчиков, вызови здесь

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +const onDocumentKeydown = (evt) => {
function, для обработчиков нам нужно всплытие

2024-06-23 12:50 UTC, wonderjs commented on js/fullsize.js
> +    onButtonCancelClick(evt);
здесь будет логичным вызов функции closeFullsizePhoto

2024-06-23 12:50 UTC, wonderjs commented on js/mocks.js
> +export {generatePhotos, createPhoto};
Убрать экспорт createPhoto

2024-06-25 15:15 UTC, wonderjs requested changes

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +import {
В целом хороший подход вынести в один модуль элементы, которые тебе нужны в нескольких модулях (например, контейнер pictures), но элементы, относящиеся к только bigPicture или только в модулю миниатюр (темплейт) тебе нужны только в модуле fullsize, так что смысла выносить их нет. Если хочешь их вынести, тогда дай всем переменным такие имена, чтобы было понятно что это - bigPicture, bigPictureImg, bigPictureLikes, miniatureTemplate и тп

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +  photo.comments.forEach((comment) => {
Не исправлено

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +    listComments.appendChild(copycomment);
Не исправлено

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +  // const pictures = document.querySelector('.pictures');
удалить ненужный код

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +const addEventListener = (photos) => {
Лучше в названии функции добавить какой это listener - addPicturesEventListener

2024-06-25 15:15 UTC, wonderjs commented on js/miniature.js
> +    puctire.setAttribute('id', photo.id);
[Д7.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d7) При использовании встроенного API, который поддерживает несколько вариантов использования, используется один способ.
Ниже ты задаешь атрибуты через точку, если хочешь использовать setAttribute / getAttribute, то нужно заменить во всех модулях по проекту. Но проще обращаться к атрибуту через точку, как ты делала до этого везде

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +    const pictureId = picture.getAttribute('id');
[Д7.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d7) При использовании встроенного API, который поддерживает несколько вариантов использования, используется один способ.

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +    const copycomment = commentOne.cloneNode(true);
Не исправлено

2024-06-25 15:15 UTC, wonderjs commented on js/fullsize.js
> +function openFullsize (photo) {
Название модуля соответствует его содержимому - fullsize-photo.js

2024-06-26 12:57 UTC, wonderjs approved these changes

2024-06-26 12:57 UTC, wonderjs commented on js/fullsize-photo.js
> +const renderComment = (photo) => {
Можно передавать сразу comments

2024-06-26 12:57 UTC, wonderjs commented on js/fullsize-photo.js
> +    const copycomment = bigPictureSocialComment.cloneNode(true);
copycomment -> newComment

2024-06-26 12:59 UTC, wonderjs commented on js/main.js
> +import { addPicturesEventListener } from './fullsize.js';
Не исправила имя файла после переименования

2024-06-26 13:07 UTC, merged