module8-task2
htmlacademy-javascript/2519719-kekstagram-1 pull request #7
Opened 2024-06-27 15:01 UTC by YarinaBarabash

2024-06-27 19:33 UTC, wonderjs requested changes

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +  const commentsPerPage = 5;
Константа, UPPER_CASE и выносим в начало модуля

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +let photo;
Тебе не обязательно хранить весь объект, достаточно будет массива comments

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +    const newCount = bigPictureCountComment.innerHTML.split(' ');
Интересный вариант, в целом рабочий, НО лучше в разметке обернуть значение с кол-вом показанных комментариев в span с каким-нибудь классом и по нему искать и заполнять содержимое элемента

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +    bigPictureCountComment.innerHTML = newCountString;
Создание переменной newCountString в целом избыточно, можно было сразу написать:
```
bigPictureCountComment.innerHTML = newCountString;
```
НО
Лучше вообще не использовать innerHTML и обернуть изменяемое значение в span с классом и для изменения значения использовать textContent.
 [Б27.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b27) Для вставки пользовательских строк (имён, фамилий и так далее) использован textContent.

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +      const copycomment = bigPictureSocialComment.cloneNode(true);
1) `copycomment` -> `newComment` (camelCase)
[Б3.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b3) Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации camelCase.
2) Лучше вынести рендер одного комментария в отдельную функцию, чтобы функции были более лаконичными и понятными

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +  document.querySelector('body').classList.add('modal-open');
Это должно быть в функции openFullsizePhoto, к рендеру комментариев это не относится

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +  const bigPictureComments = bigPicture.querySelector('.comments-count');
Вынести поиск этого элемента из функции, нам не нужно его искать при каждом вызове, он постоянно присутствует в разметке

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +  bigPictureShowMoreComments.addEventListener('click', renderComment);
[Д4.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d4) Именованные функции-обработчики событий названы в соответствии с правилами именования обработчиков.
Те делаем функцию onLoadButtonClick и там уже вызываем renderComment

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +const renderComment = () => {
Это функция рендерит не один, а сразу несколько комментариев, поэтому renderComment**s**, во мн числе

2024-06-27 19:33 UTC, wonderjs commented on js/fullsize-photo.js
> +      copycomment.querySelector('.social__text').textContent = comment.message;
Зачем тебе предыдущая строчка, если ты сразу можешь задать значение для textContent?

2024-07-01 15:50 UTC, YarinaBarabash commented on js/fullsize-photo.js
> +let photo;
y меня же вроде используется еще фото в openFullsizePhoto Оо

2024-07-01 16:11 UTC, wonderjs commented on js/fullsize-photo.js
> +let photo;
Передай в функцию openFullsizePhoto нужное фото как параметр =)

2024-07-02 09:51 UTC, wonderjs requested changes
Рабочий вариант! Осталось причесать код 

camelCase:
`onbigPictureButtonCancelClick` => `onBigPictureButtonCancelClick`

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +const COMMENTSPERPAGE = 5;
[Б7.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b7) Названия констант (постоянных значений) написаны прописными (заглавными) буквами.
Слова разделяются подчёркиваниями (UPPER_SNAKE_CASE)
`COMMENTSPERPAGE` -> `COMMENTS_PER_PAGE`

[Б10.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b10) Список констант идёт перед основным кодом.
Поднимаем наверх до переменных с let

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +const bigPictureComments = bigPicture.querySelector('.comments-count');
а почему этот элемент не вынесла в модуль elements.js?

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +  const newCount = bigPictureCountComment.querySelector('.first-comments-count');
newCount -> `shownCommentCount`
класс тоже можно назвать `shown-comments-count`, чтобы было понятно что это 

Вынести из функции, нам не нужно искать элемент при каждом вызове, достаточно один раз найти, сохранить в переменную и использовать ее

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +  if (index >= startIndex && index < endIndex) {
лучше переделать функцию renderComment, чтобы она тебе возвращала элемент комментария:
```
const getComment = (comment) => {
  const newComment = bigPictureSocialComment.cloneNode(true);
  newComment.querySelector('.social__text').textContent = comment.message;
  newComment.querySelector('.social__picture').src = comment.avatar;
  newComment.querySelector('.social__picture').alt = comment.name;
  return newComment;
};
```
А внутри `renderComments` использовать не forEach, а for, чтобы не перебирать весь массив ([Б24.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b24) Количество вызовов циклов минимизировано.), когда тебе нужно отрендерить максимум 5 элементов:
```
  for (let i = startIndex; i < endIndex; i++) {
    fragment.appendChild(getComment(photoComments[i]));
  }
```

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +  newCount.textContent = endIndex;
Переносим в `renderComments`

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +  photoComments.forEach((comment, index) => renderComment(comment, index, endIndex, fragment));
Здесь сделать for, чтобы не проходить по всему массиву

2024-07-02 09:51 UTC, wonderjs commented on js/fullsize-photo.js
> +  bigPictureShowMoreComments.addEventListener('click', renderComments);
Вынести из функции, нам не нужно вешать обработчик каждый раз, достаточно будет один

[Д4.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d4) Именованные функции-обработчики событий названы в соответствии с правилами именования обработчиков.
Либо
```
const onBigPictureShowMoreCommentsClick = () => {
  renderComments();
};

bigPictureShowMoreComments.addEventListener('click', onBigPictureShowMoreCommentsClick);
```
Либо используем анонимную функцию (подходит для случаев когда нам не нужно удалять обработчик) 
```
bigPictureShowMoreComments.addEventListener('click', () => {
  renderComments();
});
```

2024-07-02 17:22 UTC, merged