module9-task2
htmlacademy-javascript/2519719-kekstagram-1 pull request #9
Opened 2024-07-12 18:25 UTC by YarinaBarabash

2024-07-13 11:29 UTC, wonderjs requested changes

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +const MAX_SLIDER_VALUE = 100;
1) Давай вынесем работу со изменением размера в отдельный модуль, например, scale.js
2) Переменные, связанные с масштабом можно сгруппировать в перечисление:
```
const Scale = {
  STEP: 25,
  MIN: 25,
  MAX: 100,
  DEFAULT: 100
};
```

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +buttonControlBigger.onclick = function () {
1) Нарушение критерия [Д7.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d7) При использовании встроенного API, который поддерживает несколько вариантов использования, используется один способ.
2) освежи в памяти в чем разница между onclick и addEventListener "click", этот вопрос часто встречается на собеседованиях

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +  scaleControl.value = value;
Можешь вынести задание значения в отдельную функцию, чтобы не дублировать код в двух функциях:
```
const setScale = (value) => {
  scaleControl.value = `${value}%`;
  preview.style.transform = `scale(${value / 100})`;
};
```

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +    value = `${value + SCALE_STEP}%`;
1) если значение на проходит условия, то мы можем просто ничего не делать (убрать ветку else)
2) Удобнее оперировать значением без процента:
```
  if (value < Scale.MAX) {
    setScale(value + Scale.STEP);
  }
```

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +noUiSlider.create(sliderElement, {
1) Работу с эффектами тоже лучше вынести в отдельный модуль, например effects.js 
2) Для оптимизации кода модно использовать такие константы и словари:
```
const Effect = {
  NONE: 'none',
  CHROME: 'chrome',
  SEPIA: 'sepia',
  MARVIN: 'marvin',
  PHOBOS: 'phobos',
  HEAT: 'heat',
};

const effectToFilterName = {
  [Effect.NONE]: 'none',
  [Effect.CHROME]: 'grayscale',
  [Effect.SEPIA]: 'sepia',
  [Effect.MARVIN]: 'invert',
  [Effect.PHOBOS]: 'blur',
  [Effect.HEAT]: 'brightness',
};

const EFFECT_CONFIG = {
  [Effect.NONE]: {
    range: {
      min: 0,
      max: 100,
    },
    start: 100,
    step: 1,
  },
  [Effect.CHROME]: {
    ...
  },
};

```

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +const effect = {
Это переменная избыточна, все классы строятся на схеме effects__preview--эффект

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +  {
Зачем здесь скобки?

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +    switch (selectedValue) {
Подумай как можно упростить с помощью констант, которые я написала выше

2024-07-13 11:29 UTC, wonderjs commented on js/form.js
> +radioButtons.forEach((radioButton) => {
Используй детегирование, повесь обработчик на контейнер эффектов и определяй по какому произошел клик внутри

2024-07-14 13:10 UTC, wonderjs requested changes
Доработать:
- При выборе эффекта «Оригинал» слайдер и его контейнер (элемент .img-upload__effect-level) скрываются. Сейчас при первом открытии слайдер виден. 
- При закрытии формы все данные, введённые в форму, и контрол фильтра приходят в исходное состояние:
масштаб возвращается к 100%;
эффект сбрасывается на «Оригинал»;
Сейчас эффекты и масштаб не сбрасываются

2024-07-14 13:10 UTC, wonderjs commented on js/scale.js
> +const scale = {
[Б8.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b8) Название классов, конструкторов и перечислений начинается с заглавной буквы.
`scale` -> `Scale`

[Б10.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b10) Список констант идёт перед основным кодом.

2024-07-14 13:10 UTC, wonderjs commented on js/scale.js
> +  if (value >= scale.MIN) {
Неверное условие, если value будет равно 25, то получим true и в итоге установим 0%

2024-07-14 13:10 UTC, wonderjs commented on js/scale.js
> +  let value = scaleControl.value;
Избыточная переменная + не очень хорошо, что ты в нее записываешь то число, то строку

2024-07-14 13:10 UTC, wonderjs commented on js/scale.js
> +  } else {
Нужна ли ветка else?

2024-07-14 13:10 UTC, wonderjs commented on js/effects.js
> +noUiSlider.create(sliderElement, {
step тоже необходимо установить в соответсвии с ТЗ, используй EFFECT_CONFIG

2024-07-14 13:10 UTC, wonderjs commented on js/effects.js
> +const EFFECT_CONFIG = {
[Б10.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b10) Список констант идёт перед основным кодом.

2024-07-14 13:10 UTC, wonderjs commented on js/effects.js
> +  sliderElement.noUiSlider.updateOptions({
step и start также нужно задать

2024-07-14 18:38 UTC, YarinaBarabash commented on js/scale.js
> +  let value = scaleControl.value;
тогда у меня не будет работать parseInt

2024-07-15 09:08 UTC, wonderjs approved these changes

2024-07-15 09:08 UTC, wonderjs commented on js/effects.js
> +  sliderElement.noUiSlider.set(sliderCofigValue.range.max);
это можно удалить, ты выше выставляешь стартовое значение

2024-07-15 09:08 UTC, wonderjs commented on js/form.js
> +  preview.style.transform = `scale(${Scale.DEFAULT / 100})`;
Лучше в модуле scale.js сделать функцию resetScale и там сбрасывать значение на дефолтное. Функцию экспортировать из модуля и вызывать здесь:
```
const resetScale = () => {
  setScale(Scale.DEFAULT);
};
```

2024-07-15 09:08 UTC, wonderjs commented on js/scale.js
> +    value = `${value - Scale.STEP}`;
Зачем здесь шаблонная строка? Сразу передавай значение в setScale
```
  const value = parseInt(scaleControl.value, 10);
  if (value > Scale.MIN) {
    setScale(value - Scale.STEP);
  }
```

2024-07-15 09:08 UTC, wonderjs commented on js/effects.js
> +  const sliderCofigValue = EFFECT_CONFIG[value];
Опечатка Cofig -> Config
переменную назвать можно просто `config`

2024-07-15 09:08 UTC, wonderjs commented on js/elements.js
> +const preview = document.querySelector('.img-upload__preview');
Нам нужна картинка img, которая лежит в этом диве, а не сам контейнер:
```
const preview = document.querySelector('.img-upload__preview img');
```

2024-07-15 09:08 UTC, merged

2024-07-17 17:47 UTC, YarinaBarabash commented on js/elements.js
> +const preview = document.querySelector('.img-upload__preview');
тогда белый фон на картинке, но может так и надо)